export const VULNERABILITY_TYPES = [
  { id: "INJ", label: "Injection (SQL / NoSQL / Command)" },
  { id: "XSS", label: "Cross-Site Scripting (XSS)" },
  { id: "BAC", label: "Broken Access Control" },
  { id: "AUTH", label: "Authentication Issues" },
  { id: "AUTHZ", label: "Authorization Issues" },
  { id: "SDE", label: "Sensitive Data Exposure" },
  { id: "CRYPTO", label: "Cryptographic Failures" },
  { id: "MISCONF", label: "Security Misconfiguration" },
  { id: "IDOR", label: "Insecure Direct Object Reference (IDOR)" },
  { id: "CSRF", label: "Cross-Site Request Forgery (CSRF)" },
  { id: "DESER", label: "Insecure Deserialization" },
  { id: "RCE", label: "Remote Code Execution (RCE)" },
  { id: "SSRF", label: "Server-Side Request Forgery (SSRF)" },
  { id: "XXE", label: "XML External Entity (XXE)" },
  { id: "CLICK", label: "Clickjacking" },
  { id: "UPLOAD", label: "Unrestricted File Upload" },
  { id: "LOGIC", label: "Business Logic Flaw" },
  { id: "DOS", label: "Denial of Service (DoS)" },
  { id: "INFO", label: "Information Disclosure" },
  { id: "RATELIMIT", label: "Missing Rate Limiting" },
  { id: "CORS", label: "CORS Misconfiguration" },
  { id: "SESSION", label: "Session Management Issue" },
  { id: "OAUTH", label: "OAuth Misconfiguration" },
  { id: "API", label: "API Security Issue" },
  { id: "INPUT", label: "Improper Input Validation" },
  { id: "PATH", label: "Path Traversal" },
  { id: "HEADER", label: "Security Headers Missing" },
  { id: "RANDOM", label: "Weak Randomness" },
  { id: "PRIVESC", label: "Privilege Escalation" },
  { id: "OTHER", label: "Other / General" },
]

export const VULNERABILITY_SEVERITY=[
"LOW",
"MEDIUM",
"HIGH",
"CRITICAL",
]
